AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t3.micro
    Description: Enter t3.micro, t2.micro. Default is t3.micro
  InstanceImageType:
    Type: String
    Default: ami-061dbd1209944525c
  KeyPairName:
    Type: String
    Default: ansible
Resources:
    myVPCEc2SecurityGroup:
       Type: AWS::EC2::SecurityGroup
       Properties:
          GroupDescription: Allow http to client host
          GroupName: Udacity-george-sg
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
    Ec2Instance:
       Type: 'AWS::EC2::Instance'
       Properties:
          InstanceType: !Ref InstanceTypeParameter
          ImageId: !Ref InstanceImageType
          KeyName: !Ref KeyPairName          
          SecurityGroups:
            - !Ref myVPCEc2SecurityGroup
