---
 - name: "update apt packages."
   become: yes
   apt:
     update_cache: yes

 - name: "upgrade packages"
   become: yes
   apt:
     upgrade: yes

 - name: Install the gpg key for nodejs LTS
   apt_key:
     url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
     state: present
    
 - name: Install the nodejs LTS repos
   apt_repository:
     repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
     state: present
     update_cache: yes

 - name: Install the nodejs
   apt:
     name: nodejs
     state: present

 - name: "install pm2"
   become: yes
   npm:
     name: pm2
     global: yes
     production: yes
     state: present

 - name: Creates directory
   file:
     path: ~/web
     state: directory

 - name: Copy index test page
   template:
     src: "files/index.js"
     dest: "~/web/index.js"

 - name: "start application"
   shell: |
       pm2 start ~/web/index.js -f
   

